/**
 * Русские имена персонажей для поиска.
 *
 * hp-api знает только английские имена, а интерфейс у нас русский по умолчанию:
 * пользователь наберёт «Гермиона», а не «Hermione». Эти алиасы подмешиваются
 * в поисковый индекс при нормализации, поэтому поиск работает на обоих языках
 * без обращения к переводчику и без затрат в рантайме.
 *
 * Где расходятся традиции перевода (РОСМЭН и «Махаон»), указаны оба варианта:
 * Снегг/Снейп, Долгопупс/Лонгботтом, Полумна/Луна.
 */
export const RU_NAME_ALIASES: Record<string, string[]> = {
  "Harry Potter": ["гарри поттер", "избранный", "мальчик который выжил"],
  "Hermione Granger": ["гермиона грейнджер"],
  "Ron Weasley": ["рон уизли", "рональд уизли"],
  "Albus Dumbledore": ["альбус дамблдор"],
  "Severus Snape": ["северус снегг", "северус снейп", "принц полукровка"],
  "Lord Voldemort": ["волан-де-морт", "волдеморт", "тёмный лорд", "темный лорд", "сами-знаете-кто"],
  "Tom Riddle": ["том реддл", "том риддл"],
  "Draco Malfoy": ["драко малфой"],
  "Lucius Malfoy": ["люциус малфой"],
  "Narcissa Malfoy": ["нарцисса малфой"],
  "Rubeus Hagrid": ["рубеус хагрид"],
  "Sirius Black": ["сириус блэк", "бродяга"],
  "Remus Lupin": ["ремус люпин", "римус люпин", "лунатик"],
  "Neville Longbottom": ["невилл долгопупс", "невилл лонгботтом"],
  "Luna Lovegood": ["полумна лавгуд", "луна лавгуд"],
  "Ginny Weasley": ["джинни уизли"],
  "Bellatrix Lestrange": ["беллатриса лестрейндж", "беллатрикс лестрейндж"],
  "Minerva McGonagall": ["минерва макгонагалл"],
  Dobby: ["добби"],
  "Arthur Weasley": ["артур уизли"],
  "Molly Weasley": ["молли уизли"],
  "Percy Weasley": ["перси уизли"],
  "Fred Weasley": ["фред уизли"],
  "George Weasley": ["джордж уизли"],
  "Bill Weasley": ["билл уизли"],
  "Charlie Weasley": ["чарли уизли"],
  "Alastor Moody": ["аластор грюм", "грозный глаз", "аластор муди"],
  "Cedric Diggory": ["седрик диггори"],
  "Cho Chang": ["чжоу чанг", "чо чанг"],
  "Dolores Umbridge": ["долорес амбридж", "долорес эмбридж"],
  "Fleur Delacour": ["флёр делакур", "флер делакур"],
  "Victor Krum": ["виктор крам"],
  "Gilderoy Lockhart": ["златопуст локонс", "гилдерой локхарт"],
  "Sybill Trelawney": ["сивилла трелони"],
  "Filius Flitwick": ["филиус флитвик"],
  "Pomona Sprout": ["помона стебль", "помона спраут"],
  "Argus Filch": ["аргус филч"],
  "Horace Slughorn": ["гораций слизнорт", "гораций слагхорн"],
  "Nymphadora Tonks": ["нимфадора тонкс"],
  Kreacher: ["кикимер", "кричер"],
  "Peter Pettigrew": ["питер петтигрю", "хвост"],
  "Cornelius Fudge": ["корнелиус фадж"],
  "Rufus Scrimgeour": ["руфус скримджер"],
  "Gellert Grindelwald": ["геллерт гриндевальд"],
  "James Potter": ["джеймс поттер", "сохатый"],
  "Lily Potter": ["лили поттер", "лили эванс"],
  "Vernon Dursley": ["вернон дурсль"],
  "Petunia Dursley": ["петунья дурсль"],
  "Dudley Dursley": ["дадли дурсль"],
  "Oliver Wood": ["оливер вуд"],
  "Seamus Finnigan": ["симус финниган"],
  "Dean Thomas": ["дин томас"],
  "Lavender Brown": ["лаванда браун"],
  "Cormac McLaggen": ["кормак маклагген"],
  "Viktor Krum": ["виктор крам"],
  "Vincent Crabbe": ["винсент крэбб"],
  "Gregory Goyle": ["грегори гойл"],
  "Pansy Parkinson": ["пэнси паркинсон"],
  "Blaise Zabini": ["блейз забини"],
  "Padma Patil": ["падма патил"],
  "Parvati Patil": ["парвати патил"],
  "Angelina Johnson": ["анджелина джонсон"],
  "Katie Bell": ["кэти белл"],
  "Colin Creevey": ["колин криви"],
  "Rolanda Hooch": ["роланда трюк", "роланда хуч"],
  "Poppy Pomfrey": ["поппи помфри"],
  "Irma Pince": ["ирма пинс"],
  "Quirinus Quirrell": ["квиринус квиррелл"],
  "Aberforth Dumbledore": ["аберфорт дамблдор"],
  "Regulus Black": ["регулус блэк"],
  "Andromeda Tonks": ["андромеда тонкс"],
  "Ted Lupin": ["тедди люпин"],
  "Fenrir Greyback": ["фенрир сивый", "фенрир грейбек"],
  "Barty Crouch": ["барти крауч"],
  "Xenophilius Lovegood": ["ксенофилиус лавгуд"],
  Hedwig: ["букля", "хедвиг"],
  Crookshanks: ["живоглот", "косолапсус"],
  Buckbeak: ["клювокрыл", "махаон"],
  Fawkes: ["фоукс"],
  Nagini: ["нагайна", "нагини"],
  Aragog: ["арагог"],
  Norbert: ["норберт"],
  Fluffy: ["пушок"],
  "Moaning Myrtle": ["плакса миртл"],
  "Grey Lady": ["серая дама"],
  "Bloody Baron": ["кровавый барон"],
  "Nearly Headless Nick": ["почти безголовый ник"],
  "Fat Friar": ["толстый проповедник"],
  Winky: ["винки"],
  Griphook: ["крюкохват"],
  Firenze: ["флоренц"],
  Grawp: ["грохх"],
};

/** Русские названия факультетов — чтобы «слизерин» тоже находился. */
export const RU_HOUSE_ALIASES: Record<string, string[]> = {
  Gryffindor: ["гриффиндор"],
  Slytherin: ["слизерин"],
  Ravenclaw: ["когтевран", "рейвенкло"],
  Hufflepuff: ["пуффендуй", "хаффлпафф"],
};
